### PR TITLE
Remove rdf children more flexibly. Fix for #3

### PR DESCRIPTION
**Pull request by rokclimb15**

### CODE REVIEW

**Comment by diderich** [comment]
The Dublin standard requires the dc:creator to be of type seq, rather than bag as shown in the specification below:
dc_creator

Furthermore, the PR would make the delete generic for all nodes, not only `dc:creator`, which would void checking adherence to the Xmp specification.

**Comment by rokclimb15** [comment]
Hi @diderich, I understand that the format I'm replacing violates the specification, which is why I would want the write to succeed and correct the format. Would you accept another PR that was less generic and only targeted `dc:creator`? I am sure there are other containers with invalid formats, but this is the only one I have observed so far. What would be your proposed solution?

**Comment by diderich** [comment]
Here is what I would recommend:

1. Created an extension of the class `\Holiday\Metadata` , i.e. `MyMetadata`
2. Re-implement the `exportXmp` function by adding `$xmp_data->setXmpBag(Xmp::AUTHOR, false);` before `$xmp_data->setXmpSeq(Xmp::AUTHOR, $this->get(self::AUTHOR));` to clear the incorrect data element in the Xmp data. Calling `setXmpXXX()` with `false` as data will remove it.

Hpe this helps.

**Comment by rokclimb15** [comment]
Thank you @diderich !

**Pull request closed without merging**
